# -*- coding: utf-8 -*-
"""Entrega3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akiAWvzjpV6o6JvXrZCXYfFqh0sxr4sM
"""

import pandas as pd
import numpy as np

"""Entrega 3 - Analise de Dados de Vendas

Você foi contratado(a) para analisar os dados de vendas de uma loja que comercializa quatro categorias de produtos: Eletrônicos, Roupas, Alimentos e Móveis. A loja quer entender o desempenho das vendas durante o último trimestre (3 meses).
"""

dados={'Categorias':['Eletrônicos','Roupas','Alimentos','Móveis'], #Criando o conjunto de Dados para o DataFrame
       'Mês1':['Janeiro','Janeiro','Janeiro','Janeiro'],
       'pop1':[278.50,95.80,59.30,176.40],
       'Mês2':['Fevereiro','Fevereiro','Fevereiro','Fevereiro'],
       'pop2':[320.9,17.3,16.9,89.1],
       'Mês3':['Março','Março','Março','Março'],
       'pop3':[45.9,17.3,16.9,89.1]}

df1=pd.DataFrame(dados) #Criando o DataFrame

df1

"""Os dados de vendas foram registrados semanalmente, e você precisa criar um relatório que ajude a loja a tomar decisões estratégicas.

Simule os dados de vendas:

Para cada semana, gere vendas aleatórias entre 1.000 e 10.000 unidades para cada categoria.
Crie um DataFrame com 12 semanas e 4 categorias de produtos.

Análise:

Cálculo da média semanal de vendas por categoria.
Identifique a semana com a maior receita total (soma de todas as categorias).
Encontre a categoria com a maior venda acumulada no trimestre.
Reajuste de Estratégias:

Com base nos resultados, a loja decidiu:
Aumentar as vendas de Eletrônicos e Móveis em 15%.
Reduzir as vendas de Roupas em 5%.
Manter as vendas de Alimentos inalteradas.


Atualize o DataFrame para refletir essas alterações.
"""

