# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnezZMPaEeeBi5xQKfVzoD5z2X1rnt5r
"""



"""Exercícios de Fixação

Elabore um algoritmo que dada a idade de um nadador classifique-o em uma das seguintes categorias:
Infantil A = 5 a 7 anos      Juvenil B = 14 a 17 anos
Infantil B = 8 a 11 anos     Adultos   = Maiores de 18 anos
Juvenil A = 12 a 13 anos
"""

idade = int(input("Digite a idade do nadador: "))
if idade >=5 and idade <7:
    print("Infantil A")
elif idade >=14 and idade <17:
    print("Juvenil B")
elif idade >=8 and idade <11:
    print("Infantil B")
elif idade >=12 and idade <=13:
    print("Juvenil A")
else:
    print("Adulto")