# -*- coding: utf-8 -*-
"""NumpayExemplo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkgaBTmNuOO49GcFQvhlLt-QVb_ryJOn
"""

import numpy as np

#Gerar uma NDarray (2x3)
dados=np.random.rand(2,3)

#Apresenta os dados na matriz
dados

#Identifica o tipo dos dados

#Qtd e Dimensões (identifica a quantidade de linhas e colunas)
dados.shape

#idendifica a quantidade de linhas
dados.ndim

lista=[1,2,5,7.8,1.25]

dados2=np.array(lista)

dados2

lista2=[[1,2,3,4],[4,3,2,1]]

lista2

dados3=np.array(lista2)

dados3

dadoszero=np.zeros(10)

dadoszero

dadoszero2=np.zeros((2,3))

dadoszero2

dadosum=np.ones(7)

dadosum

dadosseq=np.arange(11)

dadosseq

dadosseq2=np.arange(0,21,2)

dadosseq2

dadosseq2.dtype

dadosseqfloat=dadosseq2.astype(np.float64)

dadosseqfloat

dadosseqfloat.dtype

dados4=np.array([[1,2,3],[4,5,6]])

dados4

dados4*dados4

dados4-dados4

dados5=dados4+dados4

dados5

dados6=1/dados4

dados6

dados5>dados4

dados6>dados4

dadosseq

dadosseq[3:6]

dadosseq[8:11]

dadosseq[3:6]

dadosseq[-3:] #pega os últimos 3

dadosseq[3:6]=20 #substituis os elementos no periodo do 3 ao 6, por 20

dadosseq

dadosfatiados=dadosseq[2:4]

dadosfatiados

dadosfatiados[1]=2000

dadosfatiados

dadosfatiados2=dadosfatiados[0]=10

dadosfatiados2

#Copiar Dados
dadosfatiados3=dadosseq[0:2].copy()

dadosfatiados3

dados7=np.array([[1,3,3],[1,2,3],[4,5,1]])

dados7

dados7.ndim

#Transposição de Matrizes
dados7=np.arange(15).reshape((3,5))

dados7

#fazendo a transposição:
dados7.T