# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBPBPEP97Xc6GPtVl8WX5KPwpRn7Rd2Z
"""



"""Exercício de fixação

Desenvolva um programa que recebe do usuário, o placar de um jogo de futebol (os golsde cada time) e informa se o resultado foi um empate, se a vitória foi do primeiro time ou do segundo time.
"""

placar1 = int(input("Digite o placar do primeiro time: "))
placar2 = int(input("Digite o placar do segundo time:"))

if placar1 > placar2:
    print("Vitória do primeiro time")
elif placar2 > placar1:
    print("Vitória do segundo time")
else:
    print("Empate")