# -*- coding: utf-8 -*-
"""ProjFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyrCNERVq80MxscsLbr2-FmHQJb8R4Rn
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('planilha_parsed.xlsx')

def opcao(macroDigito):
  match macroDigito:
      case 1:
        return "CENTRO"
      case 2:
        return"LESTE 1"
      case 3:
        return"LESTE 2"
      case 4:
        return"NORTE 1"
      case 5:
        return"NORTE 2"
      case 6:
        return"OESTE"
      case 7:
        return"SUL 1"
      case 8:
        return"SUL 2"
      case _:
        return"Valor inválido"

def escolhaMacroReg():
  print("Escolha uma Macrorregião pelos números abaixo:")
  print("1 - CENTRO")
  print("2 - LESTE 1")
  print("3 - LESTE 2")
  print("4 - NORTE 1")
  print("5 - NORTE 2")
  print("6 - OESTE")
  print("7 - SUL 1")
  print("8 - SUL 2")

  try:
      macroDigito = int(input("Digite o número correspondente: "))
      print("Você escolheu:", opcao(macroDigito))
      gerarGrafico(opcao(macroDigito))
  except ValueError:
      print("Por favor, insira um número válido.")


def gerarGrafico(localidade):
  macroRegDF = df[df["MACRORREGIÃO"] == localidade]
  somaFamiliasCentro = macroRegDF["TOTAL DE FAMÍLIAS"].sum()
  print(macroRegDF)
  num_distritos = macroRegDF['DISTRITOS'].count()
  distritos = macroRegDF.groupby('DISTRITOS')['TOTAL DE FAMÍLIAS'].sum().reset_index()
  plt.figure(figsize=(20, 8))
  plt.bar(distritos['DISTRITOS'], distritos['TOTAL DE FAMÍLIAS'], color='skyblue')
  plt.show()

escolhaMacroReg()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('planilha_parsed.xlsx')

somaFmlMacroReg = df.groupby("MACRORREGIÃO")["TOTAL DE FAMÍLIAS"].sum()

plt.figure(figsize=(20, 8))
plt.pie(somaFmlMacroReg,
        labels=somaFmlMacroReg.index,
        autopct='%1.1f%%',
        startangle=140,
        explode=[0, 0, 0.1, 0, 0, 0, 0, 0],
        shadow=True)
plt.show()