# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168L062XY2X93WACN7F_G2EHdihVsoUQm
"""

#importando a biblioteca necessária para lidar com estatísticas
import statistics as st
import math as mt

"""1 - Suponha que você está analisando o desempenho de um até cinco corridas diferentes. Os tempos (em minutos) que o atleta levou para completar cada corrida são os seguintes: [10,, 15, 20, 25, 30]. Você deseja calcular: a) o tempo médio que o atleta levou para completar as corridas. B) melhor tempo"""

