# -*- coding: utf-8 -*-
"""Statistics_Conjunto_Notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNnlYS-tEAninaXgXEFMeSbic6QVXSO0
"""

import statistics
import math as mt

#Definindo um conjunto de notas de alunos
notas = [7.5, 8.2, 6.9, 9.5, 5.8, 7.1, 8.6, 6.3, 9.0, 8.8]

#Calculando a média das notas
media = statistics.mean(notas)

#Calculando a mediana das notas
mediana = statistics.median(notas)

#Calculando o desvio padrão das notas
desvio_padrao = statistics.stdev(notas)

print(f"A media das notas é: {media:.2f}")

print(f"A mediana das notas é: {mediana:.2f}")

print(f"Desvio Padrão das notas é: {desvio_padrao:.2f}")