# -*- coding: utf-8 -*-
"""StatisticsHorasEstudosProfessor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZbOAW6kg8VL2QQ7A6trjV7not3jXzZE

Horas e Estudo
"""

import statistics as st

horas_estudo = [5, 7, 3, 8, 6, 4, 9, 5, 7, 6]

notas = [75, 85, 60, 90, 80, 70, 95, 75, 85, 80]

media = st.mean(horas_estudo)

media

mediana=st.median(horas_estudo)

mediana

moda = st.mode(horas_estudo)

moda

horas_estudo_1=[5, 7, 3, 8, 6]

md = st.mode(horas_estudo_1)

md

"""CORRELAÇÃO: Quanto maior a correlação, mais próximo do 0,99, mais forte a correlação, quanto mais estudar, maior a nota"""

correlacao=st.correlation(horas_estudo,notas)

correlacao

meio = len(horas_estudo) // 2

horas_estudo_low = sorted(horas_estudo)[:meio]

print(horas_estudo_low)

horas_estudo_up = sorted(horas_estudo)[meio:]

print(horas_estudos_up)

meio_notas = len(notas) // 2

notas_low = sorted(notas)[:meio_notas]

print(notas_low)

notas_up = sorted(notas)[meio_notas:]

print(notas_up)

correlacao_low = st.correlation(horas_estudo_low, notas_low)

correlacao_up = st.correlation(horas_estudo_up, notas_up)