# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYPAPhQX5TUmrDHbvWnOAscZWQoBavvr

#Definindo os dados de horas de estudos (em horas por semana) e notas
"""

#importando a biblioteca necessária para lidar com estatísticas
import statistics as st
import math as mt

#Definindo os dados de horas de estudos (em horas por semana) e notas
horas_estudo = [5, 7, 3, 8, 6, 4, 9, 5, 7, 6]
notas = [75, 85, 60, 90, 80, 70, 95, 75, 85, 80]

media_he = st.mean(horas_estudo)

print("Média:", media_he)

mediana_he = st.median(horas_estudo)

print("Mediana:", mediana_he)

moda_he = st.mode(horas_estudo)

print("Moda:", moda_he)

mediana_high_he = st.median_high(horas_estudo)

print("Mediana high:", mediana_high_he)

mediana_low_he = st.median_low(horas_estudo)

print("Mediana low:", mediana_low_he)

media_notas = st.mean(notas)

print("Média:", media_notas)

mediana_notas = st.median(notas)

print("Mediana:", mediana_notas)

moda_notas = st.mode (notas)

print("Moda:", moda_notas)

mediana_high_notas = st.median_high (notas)

print("Mediana High:", mediana_high_notas)

mediana_low_notas = st.median_low (notas)

print("Mediana Low:", mediana_low_notas)

desvio_padrao_he = st.stdev(horas_estudo)

print("Desvio padrão:", desvio_padrao_he)