# -*- coding: utf-8 -*-
"""TrabalhoNumPyCorrida.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHhMk-Zv1ILHnft2GUoTgTAlHisi_Yit

Aula 7 - Aplicação NumPy Fundamentos de Big Data e Data Science

Uma pista de kart permite 10 voltas para cada um de 6 corredores. Faça um programa que determine aleatoriamente a volta de cada corredor. Ao final, o programa deve informar:

De quem foi a melhor volta da prova, e em que volta.

Classificação final em ordem crescente.

Qual foi a volta com a média mais rápida
"""

import numpy as np

num_corredores = 6
num_voltas = 10

tempos = np.random.uniform(30, 60, (num_corredores, num_voltas))

indice_melhor_volta = np.unravel_index(np.argmin(tempos), tempos.shape)
corredor_melhor_volta = indice_melhor_volta[0] + 1
volta_melhor_volta = indice_melhor_volta[1] + 1
tempo_melhor_volta = tempos[indice_melhor_volta]

tempos_medios = np.mean(tempos, axis=1)
classificacao_final = np.argsort(tempos_medios) + 1

tempos_voltas = np.mean(tempos, axis=0)
volta_media_rapida = np.argmin(tempos_voltas) + 1
tempo_media_rapida = tempos_voltas[volta_media_rapida - 1]

print(f"Melhor volta da prova:")
print(f"Corredor {corredor_melhor_volta}, Volta {volta_melhor_volta}, Tempo: {tempo_melhor_volta:.2f} segundos\n")

print(f"Classificação final (do melhor para o pior):")
for pos, corredor in enumerate(classificacao_final, 1):
    print(f"{pos}º lugar: Corredor {corredor}, Tempo médio: {tempos_medios[corredor-1]:.2f} segundos")

print(f"\nVolta com a média mais rápida:")
print(f"Volta {volta_media_rapida}, Tempo médio: {tempo_media_rapida:.2f} segundos")